package com.william.mangoreader.daogen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_LIBRARY_MANGA_CARD".
 */
public class MyLibraryMangaCard {

    private Long id;
    /** Not-null value. */
    private String title;

    public MyLibraryMangaCard() {
    }

    public MyLibraryMangaCard(Long id) {
        this.id = id;
    }

    public MyLibraryMangaCard(Long id, String title) {
        this.id = id;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

}
