package com.william.mangoreader.daogen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LIBRARY_MANGA".
 */
public class UserLibraryManga {

    private String MangaEdenId;
    private String tab;
    /** Not-null value. */
    private String title;
    private String imageURL;
    private String genres;
    private String status;
    private Long lastChapterDate;
    private Integer hits;

    public UserLibraryManga() {
    }

    public UserLibraryManga(String MangaEdenId) {
        this.MangaEdenId = MangaEdenId;
    }

    public UserLibraryManga(String MangaEdenId, String tab, String title, String imageURL, String genres, String status, Long lastChapterDate, Integer hits) {
        this.MangaEdenId = MangaEdenId;
        this.tab = tab;
        this.title = title;
        this.imageURL = imageURL;
        this.genres = genres;
        this.status = status;
        this.lastChapterDate = lastChapterDate;
        this.hits = hits;
    }

    public String getMangaEdenId() {
        return MangaEdenId;
    }

    public void setMangaEdenId(String MangaEdenId) {
        this.MangaEdenId = MangaEdenId;
    }

    public String getTab() {
        return tab;
    }

    public void setTab(String tab) {
        this.tab = tab;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getGenres() {
        return genres;
    }

    public void setGenres(String genres) {
        this.genres = genres;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getLastChapterDate() {
        return lastChapterDate;
    }

    public void setLastChapterDate(Long lastChapterDate) {
        this.lastChapterDate = lastChapterDate;
    }

    public Integer getHits() {
        return hits;
    }

    public void setHits(Integer hits) {
        this.hits = hits;
    }

}
