package com.william.mangoreader.daogen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_LIBRARY_MANGA".
 */
public class UserLibraryManga {

    private Long id;
    private String tabs;
    /** Not-null value. */
    private String title;
    private String imageURL;
    private String status;
    private Long lastChapterDate;
    private Integer hits;

    public UserLibraryManga() {
    }

    public UserLibraryManga(Long id) {
        this.id = id;
    }

    public UserLibraryManga(Long id, String tabs, String title, String imageURL, String status, Long lastChapterDate, Integer hits) {
        this.id = id;
        this.tabs = tabs;
        this.title = title;
        this.imageURL = imageURL;
        this.status = status;
        this.lastChapterDate = lastChapterDate;
        this.hits = hits;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTabs() {
        return tabs;
    }

    public void setTabs(String tabs) {
        this.tabs = tabs;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getImageURL() {
        return imageURL;
    }

    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getLastChapterDate() {
        return lastChapterDate;
    }

    public void setLastChapterDate(Long lastChapterDate) {
        this.lastChapterDate = lastChapterDate;
    }

    public Integer getHits() {
        return hits;
    }

    public void setHits(Integer hits) {
        this.hits = hits;
    }

}
